# For more information: https://laravel.com/docs/sail
version: '3.8'
services:
    sample_api:
        container_name: sample_api
        build:
            context: .
            dockerfile: resources/docker/laravel/sail/runtimes/8.0/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                XDEBUG: '${APP_DEBUG}'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sample_network
        hostname: sample_api
        depends_on:
            - sample_mysql
        secrets:
            - DB_PASSWORD
    sample_mysql:
        container_name: sample_mysql
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD_FILE: '/run/secrets/DB_PASSWORD'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD_FILE: '/run/secrets/DB_PASSWORD'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sample_network
        hostname: sample_mysql
        secrets:
            - DB_PASSWORD

networks:
    sample_network:
        driver: bridge
volumes:
    sailmysql:
        driver: local
secrets:
    DB_PASSWORD:
        file: ./secrets/DB_PASSWORD.txt
